#!/bin/bash

### BEGIN INIT INFO
# Provides: emailstartstop
# Required-Start: $exim4 $remote_fs $syslog
# Required-Stop: $exim4 $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Send email
# Description: Sends an email at system start and shutdown
### END INIT INFO

EMAIL="root"
STARTSUBJ=`hostname`" started on "`date`
STARTBODY="Just letting you know that server "`hostname`" has started on "`date`
STOPSUBJ=`hostname`" shutdown on "`date`
STOPBODY="Just letting you know that server "`hostname`" has shutdown on "`date`
lockfile=/var/lock/subsys/emailstartstop

# Send email on startup
start() {
    echo -n $"Sending email on startup: "

    echo "${STARTBODY}" | mail -s "${STARTSUBJ}" ${EMAIL}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch $lockfile
    return 0
}

# Send email on shutdown
stop() {
    echo -n "Sending email on shutdown: "

    echo "${STOPBODY}" | mail -s "${STOPSUBJ}" ${EMAIL}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f $lockfile
    return 0
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo $"Usage: $prog {start|stop}"
        exit 2
esac
exit ${RETVAL}
