#!/bin/bash

# Tomcat7: Start/Stop Tomcat 7
#
# chkconfig: - 90 10
# description: Tomcat is a Java application Server.

. /etc/init.d/functions
. /etc/sysconfig/network

LOCAL_VAR_RUN=/var/run
LOCAL_VAR_LOCK=/var/lock/subsys
TOMCAT_USER=tomcat
DAEMON=java
CATALINA_HOME=/usr/share/apache-tomcat

THIS_ARG=$0
INIT_SCRIPT_NAME=`basename $THIS_ARG`
INIT_SCRIPT_NAME_NOEXT=${INIT_SCRIPT_NAME%.*}
LOCKFILE="$LOCAL_VAR_LOCK/$INIT_SCRIPT_NAME_NOEXT"
SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME

# Read configuration variable file if it is present
[ -r /etc/sysconfig/$INIT_SCRIPT_NAME ] && . /etc/sysconfig/$INIT_SCRIPT_NAME

export CATALINA_BASE="/srv/tomcat/$INIT_SCRIPT_NAME"
export CATALINA_PID="$LOCAL_VAR_RUN/$INIT_SCRIPT_NAME_NOEXT.pid"

# Exit if the icatalin base is not present
[ -e "$CATALINA_BASE" ] || { echo "can't find catalina base directory (CATALINA_BASE: $CATALINA_BASE)"  >&2; exit 0; }

RETVAL=0
start(){
   echo "Starting $INIT_SCRIPT_NAME_NOEXT Tomcat7 instance: "
   #su - $TOMCAT_USER -p -s /bin/bash -c "$CATALINA_HOME/bin/startup.sh"
   #runuser -l "$TOMCAT_USER" -p -s /bin/bash -c "$CATALINA_HOME/bin/startup.sh"
   $CATALINA_HOME/bin/startup.sh
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && touch $LOCKFILE
   return $RETVAL
}

stop(){
   echo "Shutting down $INIT_SCRIPT_NAME_NOEXT Tomcat7 instance: "
   $CATALINA_HOME/bin/shutdown.sh
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
   return $RETVAL
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   status)
      #status -l $(basename $LOCKFILE) -p $CATALINA_PID $DAEMON
      status -l $(basename $LOCKFILE) $DAEMON
      ;;
   *)
      echo $"Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac
exit $?

